#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

# Copy hostname file from boot partition
# if newer than hostname itself
/bin/cp -u /boot/hostname.txt /etc/hostname

# Copy wpa_supplicant file from boot partition
# if newer than current config file
/bin/cp -u /boot/wpa_supplicant.txt /etc/wpa_supplicant/wpa_supplicant.conf

# Force wpa_supplicant to reload config
/sbin/wpa_cli reconfigure

/usr/local/bin/try_adhoc_network > /home/pi/adhoc_log.txt 2>&1
iwconfig >> /home/pi/adhoc_log.txt

/usr/local/bin/install_apps > /home/pi/install_apps_log.txt 2>&1
/usr/local/bin/start_apps > /home/pi/start_apps_log.txt 2>&1

exit 0
