#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

# Copy hostname file from boot partition
# if newer than hostname itself
/bin/cp -u /boot/hostname.txt /etc/hostname

# Copy wpa_supplicant file from boot partition
# if newer than current config file
/bin/cp -u /boot/wpa_supplicant.txt /etc/wpa_supplicant/wpa_supplicant.conf

/usr/local/bin/try_adhoc_network > /home/pi/adhoc_log.txt 2>&1
iwconfig >> /home/pi/adhoc_log.txt

exit 0
