#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

/usr/local/bin/try_adhoc_network > /home/pi/adhoc_log.txt 2>&1
iwconfig >> /home/pi/adhoc_log.txt

/usr/local/bin/install_apps > /home/pi/install_apps_log.txt 2>&1
/usr/sbin/service radiodan_example-master start

exit 0
