#!/bin/bash
# RPi Network Conf Bootstrapper

createAdHocNetwork(){
  echo "Creating ad-hoc network"
  /sbin/ifconfig wlan0 down
  /sbin/iwconfig wlan0 mode ad-hoc
  /sbin/iwconfig wlan0 essid radiodanternet
  /bin/sleep 3
  /sbin/ifconfig wlan0 10.0.0.200 netmask 255.255.255.0 up
}

connected=$(/sbin/wpa_cli status | grep COMPLETED)
if [ -z "$connected" ]; then
  createAdHocNetwork
  /usr/sbin/service wpa_cli_web start
  /usr/sbin/service dnsmasq start
fi

#exit 0
