#!/usr/bin/env ruby

Dir.chdir("/home/radiodan/apps")

def execute(cmd)
  system(cmd)
end

Dir.glob("*") do |entry|
  if Dir.exists?(entry)
    Dir.chdir(entry) do
      if File.exist?("package.json")
        puts "Found NPM package for #{entry} - running npm install"
        execute "sudo -u pi npm install"
      end

      if File.exist?("Gemfile")
        puts "Found Gemfile for #{entry} - running bundle install"
        execute "sudo -u pi bundle install"
      end

      if File.exist?("Procfile")
        puts "Found Procfile for #{entry} - running procfile-upstart-exporter"
        execute "sudo procfile-upstart-exporter create --verbose --user pi --application #{entry} --path /etc/init"
      end
    end
  end
end
